// Auto-generated route map for SourceCodeButton
// Do not edit this file directly - run the generate script instead

export interface RouteInfo {
  relativePath: string;
  githubUrl: string;
}

export const RouteMap: Record<string, RouteInfo> = {
    '/(auth)/profile/[[...rest]]/page': {
      relativePath: 'src/app/(auth)/profile/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/profile/%5B%5B...rest%5D%5D/page.tsx'
    },
    '/(auth)/sign-in/[[...rest]]/page': {
      relativePath: 'src/app/(auth)/sign-in/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/sign-in/%5B%5B...rest%5D%5D/page.tsx'
    },
    '/(auth)/sign-up/[[...rest]]/page': {
      relativePath: 'src/app/(auth)/sign-up/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/sign-up/%5B%5B...rest%5D%5D/page.tsx'
    },
    '/(chat)/chat/page': {
      relativePath: 'src/app/(chat)/chat/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(chat)/chat/page.tsx'
    },
    '/(chat)/chat/settings/page': {
      relativePath: 'src/app/(chat)/chat/settings/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(chat)/chat/settings/page.tsx'
    },
    '/(chat)/chat/[threadId]/page': {
      relativePath: 'src/app/(chat)/chat/[threadId]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(chat)/chat/%5BthreadId%5D/page.tsx'
    },
    '/(shortener)/shortener/page': {
      relativePath: 'src/app/(shortener)/shortener/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(shortener)/shortener/page.tsx'
    },
    '/admin/page': {
      relativePath: 'src/app/admin/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/admin/page.tsx'
    },
    '/bgremover/page': {
      relativePath: 'src/app/bgremover/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/bgremover/page.tsx'
    },
    '/black/page': {
      relativePath: 'src/app/black/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/black/page.tsx'
    },
    '/calc/page': {
      relativePath: 'src/app/calc/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/calc/page.tsx'
    },
    '/colors/page': {
      relativePath: 'src/app/colors/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/colors/page.tsx'
    },
    '/cookies/page': {
      relativePath: 'src/app/cookies/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/cookies/page.tsx'
    },
    '/discord/page': {
      relativePath: 'src/app/discord/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/discord/page.tsx'
    },
    '/fax/page': {
      relativePath: 'src/app/fax/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/fax/page.tsx'
    },
    '/files/page': {
      relativePath: 'src/app/files/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/files/page.tsx'
    },
    '/gallery/page': {
      relativePath: 'src/app/gallery/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/gallery/page.tsx'
    },
    '/hangman/page': {
      relativePath: 'src/app/hangman/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/hangman/page.tsx'
    },
    '/home/page': {
      relativePath: 'src/app/home/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/home/page.tsx'
    },
    '/page': {
      relativePath: 'src/app/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/page.tsx'
    },
    '/todos/page': {
      relativePath: 'src/app/todos/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/todos/page.tsx'
    },
    '/white/page': {
      relativePath: 'src/app/white/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/white/page.tsx'
    }
};

// Dynamic route pattern matching
function matchDynamicRoute(pathname: string): RouteInfo | undefined {
  // Pattern for /(auth)/profile/[[...rest]]/page
  const match__auth__profile______rest___page = pathname.match(/^\/profile\/([^\/]+)](?:\/page)?$/);
  if (match__auth__profile______rest___page) {
    return {
      relativePath: 'src/app/(auth)/profile/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/profile/%5B%5B...rest%5D%5D/page.tsx'
    };
  }

  // Pattern for /(auth)/sign-in/[[...rest]]/page
  const match__auth__sign_in______rest___page = pathname.match(/^\/sign-in\/([^\/]+)](?:\/page)?$/);
  if (match__auth__sign_in______rest___page) {
    return {
      relativePath: 'src/app/(auth)/sign-in/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/sign-in/%5B%5B...rest%5D%5D/page.tsx'
    };
  }

  // Pattern for /(auth)/sign-up/[[...rest]]/page
  const match__auth__sign_up______rest___page = pathname.match(/^\/sign-up\/([^\/]+)](?:\/page)?$/);
  if (match__auth__sign_up______rest___page) {
    return {
      relativePath: 'src/app/(auth)/sign-up/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/sign-up/%5B%5B...rest%5D%5D/page.tsx'
    };
  }

  // Pattern for /(chat)/chat/[threadId]/page
  const match__chat__chat__threadId__page = pathname.match(/^\/chat\/([^\/]+)(?:\/page)?$/);
  if (match__chat__chat__threadId__page) {
    return {
      relativePath: 'src/app/(chat)/chat/[threadId]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(chat)/chat/%5BthreadId%5D/page.tsx'
    };
  }

  return undefined;
}

export function getRouteInfo(pagePath: string): RouteInfo | undefined {
  // First try exact match
  const exactMatch = RouteMap[pagePath];
  if (exactMatch) return exactMatch;

  // Then try dynamic pattern matching
  return matchDynamicRoute(pagePath);
}

export function getAllRoutes(): string[] {
  return Object.keys(RouteMap);
}
