// Auto-generated route map for SourceCodeButton
// Do not edit this file directly - run the generate script instead

export interface RouteInfo {
  relativePath: string;
  githubUrl: string;
}

export const RouteMap: Record<string, RouteInfo> = {
    '/(auth)/profile/[[...rest]]': {
      relativePath: 'src/app/(auth)/profile/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/profile/%5B%5B...rest%5D%5D/page.tsx'
    },
    '/(auth)/sign-in/[[...rest]]': {
      relativePath: 'src/app/(auth)/sign-in/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/sign-in/%5B%5B...rest%5D%5D/page.tsx'
    },
    '/(auth)/sign-up/[[...rest]]': {
      relativePath: 'src/app/(auth)/sign-up/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/sign-up/%5B%5B...rest%5D%5D/page.tsx'
    },
    '/(chat)/chat': {
      relativePath: 'src/app/(chat)/chat/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(chat)/chat/page.tsx'
    },
    '/(chat)/chat/settings': {
      relativePath: 'src/app/(chat)/chat/settings/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(chat)/chat/settings/page.tsx'
    },
    '/(chat)/chat/[threadId]': {
      relativePath: 'src/app/(chat)/chat/[threadId]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(chat)/chat/%5BthreadId%5D/page.tsx'
    },
    '/(shortener)/shortener': {
      relativePath: 'src/app/(shortener)/shortener/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(shortener)/shortener/page.tsx'
    },
    '/admin': {
      relativePath: 'src/app/admin/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/admin/page.tsx'
    },
    '/bgremover': {
      relativePath: 'src/app/bgremover/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/bgremover/page.tsx'
    },
    '/black': {
      relativePath: 'src/app/black/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/black/page.tsx'
    },
    '/calc': {
      relativePath: 'src/app/calc/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/calc/page.tsx'
    },
    '/colors': {
      relativePath: 'src/app/colors/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/colors/page.tsx'
    },
    '/cookies': {
      relativePath: 'src/app/cookies/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/cookies/page.tsx'
    },
    '/discord': {
      relativePath: 'src/app/discord/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/discord/page.tsx'
    },
    '/fax': {
      relativePath: 'src/app/fax/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/fax/page.tsx'
    },
    '/files': {
      relativePath: 'src/app/files/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/files/page.tsx'
    },
    '/gallery': {
      relativePath: 'src/app/gallery/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/gallery/page.tsx'
    },
    '/hangman': {
      relativePath: 'src/app/hangman/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/hangman/page.tsx'
    },
    '/home': {
      relativePath: 'src/app/home/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/home/page.tsx'
    },
    '/': {
      relativePath: 'src/app/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/page.tsx'
    },
    '/todos': {
      relativePath: 'src/app/todos/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/todos/page.tsx'
    },
    '/white': {
      relativePath: 'src/app/white/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/white/page.tsx'
    }
};

// Dynamic route pattern matching
function matchDynamicRoute(pathname: string): RouteInfo | undefined {
  // Pattern for /(auth)/profile/[[...rest]]
  const match__auth__profile______rest__ = pathname.match(/^\/profile\/([^\/]+)]$/);
  if (match__auth__profile______rest__) {
    return {
      relativePath: 'src/app/(auth)/profile/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/profile/%5B%5B...rest%5D%5D/page.tsx'
    };
  }

  // Pattern for /(auth)/sign-in/[[...rest]]
  const match__auth__sign_in______rest__ = pathname.match(/^\/sign-in\/([^\/]+)]$/);
  if (match__auth__sign_in______rest__) {
    return {
      relativePath: 'src/app/(auth)/sign-in/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/sign-in/%5B%5B...rest%5D%5D/page.tsx'
    };
  }

  // Pattern for /(auth)/sign-up/[[...rest]]
  const match__auth__sign_up______rest__ = pathname.match(/^\/sign-up\/([^\/]+)]$/);
  if (match__auth__sign_up______rest__) {
    return {
      relativePath: 'src/app/(auth)/sign-up/[[...rest]]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(auth)/sign-up/%5B%5B...rest%5D%5D/page.tsx'
    };
  }

  // Pattern for /(chat)/chat/[threadId]
  const match__chat__chat__threadId_ = pathname.match(/^\/chat\/([^\/]+)$/);
  if (match__chat__chat__threadId_) {
    return {
      relativePath: 'src/app/(chat)/chat/[threadId]/page.tsx',
      githubUrl: 'https://github.com/TheGloved1/gloved.dev/blob/master/src/app/(chat)/chat/%5BthreadId%5D/page.tsx'
    };
  }

  return undefined;
}

export function getRouteInfo(pagePath: string): RouteInfo | undefined {
  // First try exact match
  const exactMatch = RouteMap[pagePath];
  if (exactMatch) return exactMatch;

  // Then try dynamic pattern matching
  return matchDynamicRoute(pagePath);
}

export function getAllRoutes(): string[] {
  return Object.keys(RouteMap);
}
