import { CustomTool, CustomTools } from '@/lib/ai';

export enum Feature {
  REASONING = 'reasoning',
}
export type Features = (typeof Feature)[keyof typeof Feature][];
export type ModelID = (typeof Models)[number]['value'];
export type Model = (typeof Models)[number];
export type ModelProvider = 'google' | 'groq' | 'openrouter';
export type ModelType = 'gemini' | 'qwen' | 'llama' | 'deepseek' | 'gpt' | 'other';
export const Models = Object.freeze([
  {
    label: 'Kimi K2',
    value: 'moonshotai/kimi-k2-0905',
    provider: 'openrouter' as ModelProvider,
    type: 'other' as ModelType,
    enabled: true,
    description: 'A powerful text-to-text model, excels at writing.',
    requirements: {
      loggedIn: false,
      admin: false,
    },
    tools: [CustomTool.DND] as CustomTools,
    features: [] as Features,
  },
  {
    label: 'GPT OSS 120B',
    value: 'openai/gpt-oss-120b',
    provider: 'groq' as ModelProvider,
    type: 'gpt' as ModelType,
    enabled: true,
    description: "OpenAI's open source reasoning model",
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [CustomTool.DND, CustomTool.WEB_SEARCH] as CustomTools,
    features: [] as Features,
  },
  {
    label: 'GPT OSS 20B',
    value: 'openai/gpt-oss-20b',
    provider: 'groq' as ModelProvider,
    type: 'gpt' as ModelType,
    enabled: true,
    description: "OpenAI's open source reasoning model",
    requirements: {
      loggedIn: false,
      admin: false,
    },
    tools: [CustomTool.DND, CustomTool.WEB_SEARCH] as CustomTools,
    features: [] as Features,
  },
  {
    label: 'GPT OSS 120B (Openrouter)',
    value: 'openai/gpt-oss-120b:free',
    provider: 'openrouter' as ModelProvider,
    type: 'gpt' as ModelType,
    enabled: false,
    description: "OpenAI's open source reasoning model (free tier)",
    requirements: {
      loggedIn: false,
      admin: false,
    },
    tools: [CustomTool.DND, CustomTool.WEB_SEARCH] as CustomTools,
    features: [] as Features,
  },
  {
    label: 'Gemini 2.5 Flash Lite',
    value: 'gemini-2.5-flash-lite',
    provider: 'google' as ModelProvider,
    type: 'gemini' as ModelType,
    enabled: true,
    description: "Google's flash lite model",
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as CustomTools,
    features: [] as Features,
  },
  {
    label: 'Gemini 2.5 Flash',
    value: 'gemini-2.5-flash',
    provider: 'google' as ModelProvider,
    type: 'gemini' as ModelType,
    enabled: true,
    description: "Google's hybrid reasoning model, with a 1M token context window and thinking budgets.",
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as CustomTools,
    features: [] as Features,
  },
  {
    label: 'Gemini 2.5 Pro',
    value: 'gemini-2.5-pro',
    provider: 'google' as ModelProvider,
    type: 'gemini' as ModelType,
    enabled: true,
    description: "Google's advanced reasoning model, which excels at coding and complex reasoning tasks",
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as CustomTools,
    features: [] as Features,
  },
  {
    label: 'Qwen Coder-32b',
    value: 'qwen-2.5-coder-32b',
    provider: 'groq' as ModelProvider,
    type: 'qwen' as ModelType,
    enabled: true,
    description: 'Specialized code generation model with production-quality code output',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as CustomTools,
    features: [] as Features,
  },
  {
    label: 'Qwen qwq-32b',
    value: 'qwen-qwq-32b',
    provider: 'groq' as ModelProvider,
    type: 'qwen' as ModelType,
    enabled: true,
    description: 'Small but mighty reasoning model',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as CustomTools,
    features: [Feature.REASONING] as Features,
  },
  {
    label: 'Llama 4 Scout',
    value: 'meta-llama/llama-4-scout-17b-16e-instruct',
    provider: 'groq' as ModelProvider,
    type: 'llama' as ModelType,
    enabled: true,
    description: 'Latest open-source model from Meta',
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as CustomTools,
    features: [Feature.REASONING] as Features,
  },
  {
    label: 'Llama 4 Maverick',
    value: 'meta-llama/llama-4-maverick-17b-128e-instruct',
    provider: 'groq' as ModelProvider,
    type: 'llama' as ModelType,
    enabled: true,
    description: 'Latest open-source model from Meta. Limited to small conversations',
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as CustomTools,
    features: [Feature.REASONING] as Features,
  },
  {
    label: 'Llama 3.1-8b',
    value: 'llama-3.1-8b-instant',
    provider: 'groq' as ModelProvider,
    type: 'llama' as ModelType,
    enabled: true,
    description: 'Lightweight version of Llama 3 optimized for fast responses and efficient inference',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as CustomTools,
    features: [Feature.REASONING] as Features,
  },
  {
    label: 'Llama 3.3-70b',
    value: 'llama-3.3-70b-versatile',
    provider: 'groq' as ModelProvider,
    type: 'llama' as ModelType,
    enabled: true,
    description: 'Fast, but not the smartest',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as CustomTools,
    features: [Feature.REASONING] as Features,
  },
  {
    label: 'Groq Compound',
    value: 'groq/compound',
    provider: 'groq' as ModelProvider,
    type: 'compound' as ModelType,
    enabled: true,
    description: 'Compound is a compound AI system powered by multiple openly available models',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as CustomTools,
    features: [] as Features,
  },
] as const);
export const ModelList = Models.map((m) => m.value);
