export type Tools = 'fileTools'[];

export type Features = 'reasoning'[];

export type ModelID = (typeof Models)[number]['value'];
export type Model = (typeof Models)[number];
export type ModelProvider = 'google' | 'groq' | 'openrouter';
export type ModelType = 'gemini' | 'qwen' | 'llama' | 'deepseek' | 'gpt' | 'other';
export const Models = Object.freeze([
  {
    label: 'Kimi K2',
    value: 'moonshotai/kimi-k2-instruct-0905',
    provider: 'groq' as ModelProvider,
    type: 'other' as ModelType,
    enabled: true,
    description: 'A powerful text-to-text model, excels at writing.',
    requirements: {
      loggedIn: false,
      admin: false,
    },
    tools: [] as Tools,
    features: [] as Features,
  },
  {
    label: 'GPT OSS 120B',
    value: 'openai/gpt-oss-120b:free',
    provider: 'openrouter' as ModelProvider,
    type: 'gpt' as ModelType,
    enabled: true,
    description: "OpenAI's open source GPT OSS 120B model",
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as Tools,
    features: [] as Features,
  },
  {
    label: 'Gemini 2.5 Flash Lite',
    value: 'gemini-2.5-flash-lite',
    provider: 'google' as ModelProvider,
    type: 'gemini' as ModelType,
    enabled: true,
    description: "Google's flash lite model",
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as Tools,
    features: [] as Features,
  },
  {
    label: 'Gemini 2.5 Flash',
    value: 'gemini-2.5-flash',
    provider: 'google' as ModelProvider,
    type: 'gemini' as ModelType,
    enabled: true,
    description: "Google's hybrid reasoning model, with a 1M token context window and thinking budgets.",
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as Tools,
    features: [] as Features,
  },
  {
    label: 'Gemini 2.5 Pro',
    value: 'gemini-2.5-pro',
    provider: 'google' as ModelProvider,
    type: 'gemini' as ModelType,
    enabled: true,
    description: "Google's advanced reasoning model, which excels at coding and complex reasoning tasks",
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as Tools,
    features: [] as Features,
  },
  {
    label: 'Qwen Coder-32b',
    value: 'qwen-2.5-coder-32b',
    provider: 'groq' as ModelProvider,
    type: 'qwen' as ModelType,
    enabled: true,
    description: 'Specialized code generation model with production-quality code output',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as Tools,
    features: [] as Features,
  },
  {
    label: 'Qwen qwq-32b',
    value: 'qwen-qwq-32b',
    provider: 'groq' as ModelProvider,
    type: 'qwen' as ModelType,
    enabled: true,
    description: 'Small but mighty reasoning model',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as Tools,
    features: ['reasoning'] as Features,
  },
  {
    label: 'Llama 4 Scout',
    value: 'meta-llama/llama-4-scout-17b-16e-instruct',
    provider: 'groq' as ModelProvider,
    type: 'llama' as ModelType,
    enabled: true,
    description: 'Latest open-source model from Meta',
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as Tools,
    features: ['reasoning'] as Features,
  },
  {
    label: 'Llama 4 Maverick',
    value: 'meta-llama/llama-4-maverick-17b-128e-instruct',
    provider: 'groq' as ModelProvider,
    type: 'llama' as ModelType,
    enabled: true,
    description: 'Latest open-source model from Meta. Limited to small conversations',
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as Tools,
    features: ['reasoning'] as Features,
  },
  {
    label: 'Llama 3.1-8b',
    value: 'llama-3.1-8b-instant',
    provider: 'groq' as ModelProvider,
    type: 'llama' as ModelType,
    enabled: true,
    description: 'Lightweight version of Llama 3 optimized for fast responses and efficient inference',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as Tools,
    features: ['reasoning'] as Features,
  },
  {
    label: 'Llama 3.3-70b',
    value: 'llama-3.3-70b-versatile',
    provider: 'groq' as ModelProvider,
    type: 'llama' as ModelType,
    enabled: true,
    description: 'Fast, but not the smartest',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as Tools,
    features: ['reasoning'] as Features,
  },
  {
    label: 'Deepseek R1 (OpenRouter)',
    value: 'deepseek/deepseek-r1-0528:free',
    provider: 'openrouter' as ModelProvider,
    type: 'deepseek' as ModelType,
    enabled: true,
    description: 'DeepSeek R1 from OpenRouter',
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as Tools,
    features: ['reasoning'] as Features,
  },
  {
    label: 'Deepseek R1 (Qwen Distill)',
    value: 'deepseek-r1-distill-qwen-32b',
    provider: 'groq' as ModelProvider,
    type: 'qwen' as ModelType,
    enabled: true,
    description: 'DeepSeek R1, distilled on Qwen 32b',
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as Tools,
    features: [] as Features,
  },
  {
    label: 'Deepseek R1 (Llama Distill)',
    value: 'deepseek-r1-distill-llama-70b',
    provider: 'groq' as ModelProvider,
    type: 'llama' as ModelType,
    enabled: true,
    description: 'DeepSeek R1, distilled on Llama 3.3 70b',
    requirements: {
      loggedIn: true,
      admin: false,
    },
    tools: [] as Tools,
    features: ['reasoning'] as Features,
  },
  {
    label: 'Groq Compound',
    value: 'groq/compound',
    provider: 'groq' as ModelProvider,
    type: 'compound' as ModelType,
    enabled: true,
    description: 'Compound is a compound AI system powered by multiple openly available models',
    requirements: {
      loggedIn: true,
      admin: true,
    },
    tools: [] as Tools,
    features: [] as Features,
  },
] as const);
export const ModelList = Models.map((m) => m.value);
